### PR TITLE
Add basic readme

### PR DESCRIPTION
**Pull request by Ainali**
The files will expand as we add more files and details about the repository itself.

### CODE REVIEW

**Comment by janhalen** [comment]
Will there be both a "meta" README describing what this repo is about and a "content" "README_template" that is what is part of the template you would clone but in another folder structure or separated some other way?

**Comment by Ainali** [comment]
> Will there be both a "meta" README describing what this repo is about and a "content" "README_template" that is what is part of the template you would clone but in another folder structure or separated some other way?

Yes, there will be files describing how this repository is managed and, of course, the actual templates themselves. We are waiting to add them until we have decided if we want to name them with `_template` or put them in a templates directory.

**Comment by danneleaf** [comment]
I dont have much to comment - its a good start and I like that we have the roadmap included at this early stage :)

**Review by danneleaf — APPROVED** [review]

**Comment by janhalen** [comment]
Ok.. great.. LGTM then!

**Pull request merged**
